### ISSUE TITLE
Doc for "Build C/C++ code on the fly"

### ISSUE THREAD

**Issue by bardo84** [nelson-lang/nelson#1110]
[This](https://nelson-lang.github.io/nelson-website/EXTERNAL_MODULE.html)
shows a screenshot with command 
generatecmake
The [doc](https://nelson-lang.github.io/nelson-website/help/en_US/index.html)
does not help.

Awesome work!

**Comment by Nelson-numerical-software** [comment]
I could add this:
![image](https://github.com/nelson-lang/nelson/assets/23081266/b82e447d-83b6-4af9-a157-6bf60ada3b23)

Text or contribution to increase documentation or code is welcome ;) @bardo84

**Comment by bardo84** [comment]
Hi,
screenshot of proposed solution->ocr->AI prettyprint
-> improve the workflow.

Had to change CDESTFILE -> C_DEST_FILE

[res, message] = dlmake(DEST_DIR);
executes without warning, but no dll file is generated.

**Comment by Nelson-numerical-software** [comment]
code is available here:
https://github.com/nelson-lang/nelson/pull/1111/files
or here:
https://nelson-lang.github.io/nelson-website/BUILD_C_CPP_ON_FLY.html

If you have some warnings or trouble, can you tell me more about your configuration
- windows, linux ?
- version 1.2.0.0 ?
- which compiler have you installed on your pc

Thanks for your interest

**Comment by bardo84** [comment]
Windows 
1.2.0.3744 (Fortitude)
Msys2 MINGW64

Merci

**Comment by Nelson-numerical-software** [comment]
I suppose that you configure mingw path just before with `configuremingw`

https://nelson-9.gitbook.io/nelson/en/dynamic_link/configuremingw
what is the outputs (message) of 

```
if ispc() && ~havecompiler()
configuremsvc()
end
C_CONTENT = ["double";
"functionC(double x)";
"{";
"    return x + 8;";
"}"];
DEST_DIR = [tempdir(), 'example_C'];
mkdir(DEST_DIR);
C_DEST_FILE = [tempdir(), 'example_C/demo.c'];
filewrite(C_DEST_FILE, C_CONTENT)

[res, message] = dlgeneratemake(DEST_DIR, 'C_DEMO', {C_DEST_FILE}, {DEST_DIR})
[res, message] = dlmake(DEST_DIR)

lib = dlopen([DEST_DIR, '/C_DEMO', getdynlibext()])
c = dllibinfo(lib)

f = dlsym(lib, 'functionC', 'double', {'double'});
R = dlcall(f, 3) % 8 + 3
dlclose(lib)
```

**Comment by bardo84** [comment]
Working now.
[res, message] = configuremingw(mingw_path)
I had to actually use the bin directory,  mingw_bin_path?

- When pasting a code block into the command pane, intermediate errors are not shown.
- Copying from the command pane via select/CTRL-C does not work. Right mouse click visually unselects, but works.

Would it be possible to generate stand-alone code as well?
(That was what I was downloading Nelson for).

Merci

**Comment by Nelson-numerical-software** [comment]
"Would it be possible to generate stand-alone code as well?"
Code generation without dependency to nelson is currently not possible (later)
Currently you need to call nelson as engine (minimal version can be < 11mo, lgpl no trouble to distribute)
You can call nelson as mex engine see example : https://github.com/nelson-lang/nelson/blob/master/modules/mex/examples/mex_engine_demo_1.m
