### ISSUE TITLE
Matrix Parsing/Evaluation Bug 

### ISSUE THREAD

**Issue by rdbyk** [nelson-lang/nelson#1200]
**Describe the bug**

An expression "[ ... ]" to create a matrix, which contains variables throws an error and does
not create the matrix as expected.

**To Reproduce**

a=1;b=2;c=3;
A=[a a a; b b b; c c c]

**Expected behavior**

Matrix A should be be created without error.

**Screenshots**

![Screenshot from 2024-05-28 07-44-59](https://github.com/nelson-lang/nelson/assets/25689704/b2a0159d-81dd-4894-bd5a-16dc9ed7ce5b)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04

**Additional context**
None.

**Comment by Nelson-numerical-software** [comment]
Temp workaround:
```matlab
 A=[a, a, a; b, b, b; c, c, c]
```

**Comment by rdbyk** [comment]
Ok, thanks!

**Comment by Nelson-numerical-software** [comment]
matlab also allow:  A=[-0.095-0.021j,-1]

**Comment by Nelson-numerical-software** [comment]
in progress ...
![image](https://github.com/nelson-lang/nelson/assets/23081266/b55a0a37-bf71-4bfd-a192-65cd06e7ebe0)
