### ISSUE TITLE
Matrix Exponential (expm) might give deadly wrong results

### ISSUE THREAD

**Issue by rdbyk** [nelson-lang/nelson#1201]
**Describe the bug**

This seems to be related to a rather old M***** bug cf. [https://blogs.mathworks.com/cleve/2012/07/23/a-balancing-act-for-the-matrix-exponential/#7401fe8a-5a7d-40df-92d7-1ae34f45adf2](url)

**To Reproduce**
![Screenshot from 2024-05-28 08-04-15](https://github.com/nelson-lang/nelson/assets/25689704/f5f83c03-fe1e-45db-999c-7df084c2c912)

**Expected behavior**

cf. [https://blogs.mathworks.com/cleve/2012/07/23/a-balancing-act-for-the-matrix-exponential/#7401fe8a-5a7d-40df-92d7-1ae34f45adf2](url)

**Screenshots**
cf. above

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04

**Additional context**
might be interesting, to have a look at
[https://nhigham.com/2016/03/08/the-improved-matlab-functions-expm-and-logm/](url)
[https://nhigham.com/2020/03/27/update-of-catalogue-of-software-for-matrix-functions/](url)

**Comment by Nelson-numerical-software** [comment]
contribution is welcome :)

**Comment by Nelson-numerical-software** [comment]
```matlab
format long g
a = 2e10;
b = 4e8/6;
c = 200/3;
d = 3;
e = 1e-8;
A = [0, e, 0; -(a+b), -d, a; c, 0, -c]
E = expm(A)
```

**Comment by Nelson-numerical-software** [comment]
current algo call eigen library
https://github.com/nelson-lang/nelson/blob/0c5a5a0c3d6ee6d02c8daca24b73c947fe6b68e4/modules/linear_algebra/src/cpp/ExpMatrix.cpp#L53

need to report bug or change code
https://github.com/cran/expm/blob/master/src/expm.c (?)

**Comment by Nelson-numerical-software** [comment]
Temp workaround:

 expm(complex(A))
![image](https://github.com/nelson-lang/nelson/assets/23081266/ef1c1704-9f39-4786-938f-72909a897f66)

**Comment by Nelson-numerical-software** [comment]
bug "dedicated" to Nick Higham (RIP)

**Comment by rdbyk** [comment]
This matrix exponential stuff is a pain ... the Eigen matrix exponential function seems to be from
the "unsupported" section ...

But why don't use just the same approach for real matrices as you did for the complex case, i.e.

[V,D]=eig(A)
E = V*diag(exp(diag(D)))*inv(V)

and maybe just implement it as a Nelson function for the time being  and not a builtin to ease future
modifications ?

At least this seems to be faster, than the workaround "expm(complex(A))" ...

![Screenshot from 2024-05-29 11-06-26](https://github.com/nelson-lang/nelson/assets/25689704/d122fd61-9341-4a3a-9580-f94c349567ca)

Best wishes!

**Comment by Nelson-numerical-software** [comment]
need to be refactored for 1.6
![image](https://github.com/nelson-lang/nelson/assets/23081266/85d57da3-84dd-4991-926c-47ac80c04ce2)

**Comment by Nelson-numerical-software** [comment]
```
format long g
a = 2e10;
b = 4e8/6;
c = 200/3;
d = 3;
e = 1e-8;
A_IN = [0, e, 0; -(a+b), -d, a; c, 0, -c];
N = 3;
NDIAG = 9;
DELTA = 1.0;
BALANC = 'S';
[A_OUT, MDIG, IDIG, IWARN, INFO] = slicot_mb05od(BALANC, NDIAG, DELTA, A_IN);
A_OUT
```
result is good but slower

With `A = [1 -1 -1;0 1 -1; 0 0 1];`

```
 [V,D]=eig(A)
E = V*diag(exp(diag(D)))*inv(V)
```
result is wrong in this case

Need more investigation
