### ISSUE TITLE
Function "diag" may return wrong sub- or superdiagonals

### ISSUE THREAD

**Issue by rdbyk** [nelson-lang/nelson#1205]
**Describe the bug**

![Screenshot from 2024-06-02 13-00-19](https://github.com/nelson-lang/nelson/assets/25689704/0aceba02-b9df-463d-a5e0-9ece8d3468f6)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04

**Comment by Nelson-numerical-software** [comment]
result expected: 
```diag(A,3)' == diag(A,4)'```
diag(A,n) with n > ndims(A)

**Comment by Nelson-numerical-software** [comment]
@rdbyk  thanks :)
