### ISSUE TITLE
Function "bode" does not unwrap phase

### ISSUE THREAD

**Issue by rdbyk** [nelson-lang/nelson#1210]
**To Reproduce**
![Screenshot from 2024-06-04 16-01-39](https://github.com/nelson-lang/nelson/assets/25689704/4f2ed310-da83-482c-913b-5dcc381ac895)

**Expected behavior**
![Screenshot from 2024-06-04 15-59-45](https://github.com/nelson-lang/nelson/assets/25689704/aaa87d16-2038-4982-bbc1-84c203095eca)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04

**Additional context**
Please note, that M****b has an "unwrap" function as well.

**Comment by Nelson-numerical-software** [comment]
https://koor.fr/Python/API/scientist/numpy/unwrap.wp

**Comment by Nelson-numerical-software** [comment]
any chance that you contribute to this code ? :) @rdbyk

**Comment by rdbyk** [comment]
May be ;-)

I thought about using/porting

[https://github.com/gnu-octave/octave/blob/7b28e1948cffb91871e818009e5a1eb4b265cec6/scripts/signal/unwrap.m#L1](url)

I will have a look, but it may take some time ...

**Comment by Nelson-numerical-software** [comment]
no time pressure :)

**Comment by rdbyk** [comment]
A minimal solution to fix the `bode` function regarding phase unwrapping

https://github.com/rdbyk/nelson/commit/38cf6880502d512432c85257e75b0e92dca6099a

**Comment by Nelson-numerical-software** [comment]
@rdbyk  thanks.
Do you want to create a PR from your repo or create it ? :)
